version: "2.1"
services:
  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=10.2.40.101